### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by YarNayar** [rslota/ex_assert_eventually#1]
Hello,

I'm curious if it's intentional behaviour that condition check inside `eventually` triggered at least twice even if the first call of it yields a successful result?

To demonstrate this I tweaked one of your tests:
```
    test "when match is successful from the first try" do
      {:ok, mock} =
        start_supervised(
          {MockOperation, [success_return: :ok, failure_return: :error, fail_times: 0]}
        )

      returne_value = assert_eventually :ok = MockOperation.do_something(mock), :ok

      assert returne_value == :ok

      stats = MockOperation.get_stats(mock)
      # by default there should be one call each 20ms
      assert stats.call_counter ==  1
    end
```
This test will fail as call_counter is gonna be equal `2` and not `1` even though the condition was met after the first call of eventually "block".

I looked through the tests and my guess is that you might have thought of scenarios when the state eventually settles and the assertion yields the same results from one point onward. But imagine the scenario when you getting messages from the queue and you are not sure whether the message is ready to be consumed or delay is required. `assert_eventually` looks like the right tool for this job, right? Wrong! If it's just one message and it's ready to be consumed by the time of the first call, it's gonna fetch it with the first call and will fail ugly later on even though the condition of assertion was met. This behaviour is unexpected and it took me some time to figure why my test fails as the matcher basically breaks the expectation of how it should behave. 

Would it be possible to change that so `assert_eventually` would be useful in the scenario I described as well?

**Comment by rslota** [comment]
Hi @YarNayar !

Indeed the initial design assumed that since the condition is uncertain to be successful on 1st try, it shouldn't really matter how many times it will be checked before it succeeds. The fact that condition is checked twice is just a byproduct of the "simplest" approach to this check, but since this is not 1st request like that, I'm gonna try to take a look a this.

**Comment by YarNayar** [comment]
Well, thanks for replying in such a timely manner! Basically, the scenario you need to reproduce is to make you `Mock` return [:ok, :error, :error....... and so on, errors to the end] and call `assert_eventually` with `:ok` expected. It will never succeed even though the condition was met at the first call.
